//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_benifit
    {
        public long id { get; set; }
        public long User_id { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
        public string comments { get; set; }
        public byte type { get; set; }
    
        public virtual db_User db_User { get; set; }
    }
}
