//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Cell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Cell()
        {
            this.db_Emp_Cell = new HashSet<db_Emp_Cell>();
            this.db_Employee = new HashSet<db_Employee>();
            this.db_Order_Detail = new HashSet<db_Order_Detail>();
        }
    
        public long Cell_Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public bool Status { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Dep_id { get; set; }
        public string Short_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Emp_Cell> db_Emp_Cell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Employee> db_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Order_Detail> db_Order_Detail { get; set; }
    }
}
