//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Employee()
        {
            this.db_Emp_Cell = new HashSet<db_Emp_Cell>();
            this.db_image = new HashSet<db_image>();
            this.db_User = new HashSet<db_User>();
            this.db_Order_Detail = new HashSet<db_Order_Detail>();
        }
    
        public long Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Bank_Id { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public long Present_Posting { get; set; }
        public long Department { get; set; }
        public string Present_Address { get; set; }
        public long Category_Id { get; set; }
        public bool Status { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public long Work_Id { get; set; }
        public long Cell_Id { get; set; }
        public long Designation_Id { get; set; }
        public string Bn_Emp_Name { get; set; }
        public Nullable<System.DateTime> promotion_Date { get; set; }
    
        public virtual db_Cell db_Cell { get; set; }
        public virtual db_Department db_Department { get; set; }
        public virtual db_Department db_Department1 { get; set; }
        public virtual db_Designation db_Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Emp_Cell> db_Emp_Cell { get; set; }
        public virtual db_Job_Cate db_Job_Cate { get; set; }
        public virtual db_Work_Category db_Work_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_image> db_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_User> db_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Order_Detail> db_Order_Detail { get; set; }
        public string Imagetext { get; set; }
        public List<long> list_db_Emp_Cell { get; set; }
    }
}
