//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_image
    {
        public long id { get; set; }
        public byte[] image { get; set; }
        public long Emp_Id { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual db_Employee db_Employee { get; set; }
        public virtual db_User db_User { get; set; }
    }
}
