//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Log
    {
        public long Log_Id { get; set; }
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Category { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual db_User db_User { get; set; }
    }
}
