//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Order_Detail
    {
        public long Order_Detail_Id { get; set; }
        public long Order_Id { get; set; }
        public long Emp_Id { get; set; }
        public long Cell_Id { get; set; }
        public long Work_Id { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Start_time { get; set; }
        public System.TimeSpan End_time { get; set; }
        public string Detail { get; set; }
        public string Refno { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
    
        public virtual db_Cell db_Cell { get; set; }
        public virtual db_Employee db_Employee { get; set; }
        public virtual db_Order db_Order { get; set; }
        public virtual db_User db_User { get; set; }
        public virtual db_Work_Category db_Work_Category { get; set; }

        public string From_Dateall { get; set; }
    }
}
