//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Order()
        {
            this.db_Order_Detail = new HashSet<db_Order_Detail>();
        }
    
        public long Order_Id { get; set; }
        public string Order_No { get; set; }
        public System.DateTime Date { get; set; }
        public string Detail { get; set; }
        public string Refno { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<System.DateTime> EnDate { get; set; }
    
        public virtual db_User db_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Order_Detail> db_Order_Detail { get; set; }
    }
}
