//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Work_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Work_Category()
        {
            this.db_Employee = new HashSet<db_Employee>();
            this.db_work_text = new HashSet<db_work_text>();
            this.db_Order_Detail = new HashSet<db_Order_Detail>();
        }
    
        public long Work_Id { get; set; }
        public string Name { get; set; }
        public long User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public Nullable<decimal> Entertainment { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public string Detail { get; set; }
        public Nullable<int> work_type { get; set; }
        public Nullable<long> Cell_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Employee> db_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_work_text> db_work_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Order_Detail> db_Order_Detail { get; set; }
    }
}
