//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office_Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMDATA
    {
        public string ID { get; set; }
        public Nullable<int> SL_NO { get; set; }
        public string TM_FOR { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string PURPOSE_CODE { get; set; }
        public string BENEFICIARY_DETAILS { get; set; }
        public string APPLICANT_NAME { get; set; }
        public string APPLICANT_ADDRESS { get; set; }
        public Nullable<decimal> EFFECTED_REMITTANCE { get; set; }
        public string FX_MANUAL_PARA { get; set; }
        public string BB_APPROVAL_NO { get; set; }
        public string APPROVAL_DATE { get; set; }
        public Nullable<int> CATEGORY_CODE { get; set; }
        public Nullable<System.DateTime> TM_DATE { get; set; }
        public Nullable<int> COMPANY_TYPE_ID { get; set; }
        public Nullable<decimal> MOP_CASH { get; set; }
        public Nullable<decimal> MOP_TC { get; set; }
        public Nullable<decimal> MOP_CARD { get; set; }
        public Nullable<decimal> MOP_FDD { get; set; }
        public Nullable<decimal> MOP_MT { get; set; }
        public Nullable<decimal> MOP_OTHER { get; set; }
        public Nullable<decimal> SFC_BANK { get; set; }
        public Nullable<decimal> SFC_FC_AC { get; set; }
        public Nullable<decimal> SFC_ERQ { get; set; }
        public Nullable<decimal> SFC_OTHER { get; set; }
        public Nullable<decimal> AMOUNT_IN_BDT { get; set; }
        public string CONTACT_NO { get; set; }
        public byte[] BANK_REFERENCE { get; set; }
        public string PASSPORT { get; set; }
        public string PASSPORT_NO { get; set; }
        public string CITIZEN_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> PASSPORT_DATE { get; set; }
        public string PASSPORT_ISSUE_PLACE { get; set; }
        public Nullable<System.DateTime> PASSPORT_RENEWAL_DATE { get; set; }
    }
}
